<a href="https://colab.research.google.com/github/ujjwalkuikel/PyTorch-Learning/blob/main/Pytorch_crash_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Basics

Tensor is a multidimensional matrix containing elements of single data types.

Tensors are just a flexible way to store and work with numbers, no matter how many dimensions.

In [2]:
import torch

Empty tensors

In [3]:
x = torch.empty(1);
print(x);

x = torch.empty(2,3);
print(x);

x = torch.empty(2,3,4);
print(x);

tensor([0.])
tensor([[ 1.8900e+03,  0.0000e+00, -1.6121e+36],
        [ 4.5789e-41,  8.9683e-44,  0.0000e+00]])
tensor([[[ 1.8796e+03,  0.0000e+00,  1.4013e-45,  0.0000e+00],
         [ 1.8795e+03,  0.0000e+00,  1.8795e+03,  0.0000e+00],
         [ 3.3631e-44,  1.8469e+25,  1.3877e-38,  0.0000e+00]],

        [[ 2.8026e-45,  4.9379e+33,  5.1615e-14,  6.0102e-39],
         [ 9.8091e-45,  0.0000e+00,  9.8091e-45,  1.4013e-45],
         [ 3.3631e-44,  1.0842e-19, -5.0455e+30,  4.5789e-41]]])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.6289, 0.3830, 0.5691],
        [0.2989, 0.7825, 0.7923],
        [0.9474, 0.9406, 0.4005],
        [0.8833, 0.1273, 0.6154],
        [0.7856, 0.2495, 0.8295]])


In [5]:
torch.zeros(5,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
y = torch.ones(2,5)

In [7]:
y.size()

torch.Size([2, 5])

In [8]:
print(x.dtype)

torch.float32


Datatype can be specified like
tensor.zeroes(2,3,dtype = torch.float16)

In [9]:
torch.ones(2,5,5, dtype = torch.int32)

tensor([[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]], dtype=torch.int32)

In [10]:
x = torch.tensor([2,5])
print(x, x.dtype)

tensor([2, 5]) torch.int64


By default require_grad is False.
It means it will need to calc gradient for this tensor.


Gradients tell us:
Which way and how much to tweak these numbers to improve the outcome.


In [11]:
x = torch.tensor([2,5], requires_grad=False)


In [12]:
#Operations
z = x+y
# or
torch.add(x,y)

RuntimeError: The size of tensor a (2) must match the size of tensor b (5) at non-singleton dimension 1

In [13]:
#To reshape tensor "view"

x = torch.randn(4,4)

y= x.view(16)

In [14]:
abc = x.numpy()

In [15]:
print(type(abc))

<class 'numpy.ndarray'>


In [16]:
# numpy to tensor
tensor = torch.from_numpy(abc)
tensor

tensor([[-0.0448,  1.9171, -0.0235,  0.3551],
        [ 1.4915,  1.0467, -0.7103, -1.4168],
        [-0.9307,  0.6405,  0.2344,  0.1327],
        [-1.5435, -1.3511, -1.0510,  0.4797]])

In [17]:
torch.tensor(abc)

tensor([[-0.0448,  1.9171, -0.0235,  0.3551],
        [ 1.4915,  1.0467, -0.7103, -1.4168],
        [-0.9307,  0.6405,  0.2344,  0.1327],
        [-1.5435, -1.3511, -1.0510,  0.4797]])

GPU, CPU

In [18]:
device = torch.device("cuda" if torch.cuda.is_available else "cpu")

In [19]:
## moving
x = torch.randn(2,2).to(device)

In [20]:
## creating in GPU
z = torch.randn(9, device = device)

## Autograd

Autograd provides automatic differentiation for all operations on Tensors.

It’s a system that automatically calculates gradients (derivatives) for tensors.

**How does it work in practice?**


1. You create tensors with requires_grad=True.

2. Perform operations on them — PyTorch remembers how they were created.

3. Call .backward() on a result tensor to compute gradients.

4. Access .grad on the original tensors to see their gradients.


**What is torch.autograd?**

-> torch.autograd is the PyTorch submodule that powers automatic differentiation — it’s short for "automatic gradient".


Think of it as the engine that:
* Records how tensors were computed (the computation graph),
* And then computes the gradients (backward pass) when asked.

In [22]:
x = torch.randn(3,requires_grad = True)

In [23]:
y = x+2

print(x)

print(y)

print(y.grad_fn)

tensor([ 0.2269, -0.0405, -1.4444], requires_grad=True)
tensor([2.2269, 1.9595, 0.5556], grad_fn=<AddBackward0>)


In [24]:
z = 3*y**2
print(z)

tensor([14.8773, 11.5192,  0.9260], grad_fn=<MulBackward0>)


In [25]:
z = z.mean()
print(z)

tensor(9.1075, grad_fn=<MeanBackward0>)


In [26]:
print(x.grad)

None


In [28]:
z.backward()
print(x.grad)

tensor([4.4538, 3.9190, 1.1112])


`.backward()` accumulates the gradient for this tensor into .grad attribute

Also, be careful during optmization. `optimizer.zero_grad()`


To stop a tensor from tracking history
we can use


*   `x.requires_grad(false)`
* `x.detach()`
*   wrap in `with torch.nograd():


---



In [29]:
a = torch.randn(2,2)

In [30]:
b = (a*a).sum()

In [31]:
print(a.requires_grad)

False


None


In [52]:
a = torch.randn(3,3)
a.requires_grad_(True)
b = (a*a).sum()
print(a.requires_grad)
print(b.grad_fn)

True


In [53]:
print(b.requires_grad)

True


In [54]:
b = a.detach()
print(b)

tensor([[ 1.4092, -0.1521, -0.1175],
        [-0.7127,  1.4477,  1.3607],
        [ 0.7478,  0.2619, -0.5850]])


In [55]:
a = torch.randn(3,3)
a.requires_grad_(True)
b = (a*a).sum()
print(a.requires_grad)
print(b.grad_fn)

True


In [57]:
with torch.no_grad():
  b = (a*a).sum()
  print(b.grad_fn)

None


### LR using Autograd

In [72]:
x = torch.tensor([1,2,3,4,5,6],dtype = torch.float32)
y = torch.tensor([3,6,9,12,15,18],dtype = torch.float32)

In [73]:
w = torch.tensor(0.0,dtype=torch.float32,requires_grad=True)

In [74]:
def forward(x):
  return w*x

In [75]:
def loss(y,y_pred):
  return ((y_pred-y)**2).mean()

In [76]:
x_test = 4
print(f'prediction before training: f({x_test}) = {forward(x_test).item():.3f}')

prediction before training: f(4) = 0.000


In [77]:
learning_rate = 0.01
n_epochs = 1000

for epoch in range(n_epochs):
  y_pred = forward(x)

  l = loss(y,y_pred)

  l.backward()

  with torch.no_grad():
    w-= learning_rate * w.grad


  w.grad.zero_()


print(f'prediction after training: f({x_test}) = {forward(x_test).item():.3f}')




prediction after training: f(4) = 12.000


In [80]:
x_test = 9

In [81]:
print(f'prediction after training: f({x_test}) = {forward(x_test).item():.3f}')


prediction after training: f(9) = 27.000


### Model Loss and Optimizer