<a href="https://colab.research.google.com/github/ujjwalkuikel/PyTorch-Learning/blob/main/Pytorch_crash_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Basics

Tensor is a multidimensional matrix containing elements of single data types.

Tensors are just a flexible way to store and work with numbers, no matter how many dimensions.

In [2]:
import torch

Empty tensors

In [3]:
x = torch.empty(1);
print(x);

x = torch.empty(2,3);
print(x);

x = torch.empty(2,3,4);
print(x);

tensor([0.])
tensor([[1.4414e+23, 4.3068e-41, 1.4414e+23],
        [4.3068e-41, 4.4842e-44, 0.0000e+00]])
tensor([[[6.1875e-31, 0.0000e+00, 1.4414e+23, 4.3068e-41],
         [4.4842e-44, 7.9874e-44, 6.2226e-31, 0.0000e+00],
         [1.5807e-42, 0.0000e+00, 6.2226e-31, 0.0000e+00]],

        [[1.6816e-44, 0.0000e+00, 4.6243e-44, 0.0000e+00],
         [6.2252e-31, 0.0000e+00, 6.2216e-31, 0.0000e+00],
         [1.7937e-43, 0.0000e+00, 1.5695e-43, 0.0000e+00]]])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.5999, 0.0507, 0.8370],
        [0.3769, 0.4875, 0.2206],
        [0.6262, 0.8951, 0.5556],
        [0.5340, 0.3502, 0.4480],
        [0.8111, 0.1749, 0.0542]])


In [5]:
torch.zeros(5,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [13]:
y = torch.ones(2,5)

In [25]:
y.size()

torch.Size([2, 5])

In [26]:
print(x.dtype)

torch.int64


Datatype can be specified like
tensor.zeroes(2,3,dtype = torch.float16)

In [27]:
torch.ones(2,5,5, dtype = torch.int32)

tensor([[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]], dtype=torch.int32)

In [28]:
x = torch.tensor([2,5])
print(x, x.dtype)

tensor([2, 5]) torch.int64


By default require_grad is False.
It means it will need to calc gradient for this tensor.


Gradients tell us:
Which way and how much to tweak these numbers to improve the outcome.


In [29]:
x = torch.tensor([2,5], requires_grad=False)


In [30]:
#Operations
z = x+y
# or
torch.add(x,y)

RuntimeError: The size of tensor a (2) must match the size of tensor b (5) at non-singleton dimension 1

In [31]:
#To reshape tensor "view"

x = torch.randn(4,4)

y= x.view(16)

In [40]:
abc = x.numpy()

In [41]:
print(type(abc))

<class 'numpy.ndarray'>


In [43]:
# numpy to tensor
tensor = torch.from_numpy(abc)
tensor

tensor([[-0.1766,  0.1665, -0.2930, -0.4493],
        [-0.9041, -0.0255, -0.5156,  1.0865],
        [ 0.7618,  0.8397,  1.7780,  0.4310],
        [-0.2759,  0.6048, -0.7045,  0.9444]])

In [44]:
torch.tensor(abc)

tensor([[-0.1766,  0.1665, -0.2930, -0.4493],
        [-0.9041, -0.0255, -0.5156,  1.0865],
        [ 0.7618,  0.8397,  1.7780,  0.4310],
        [-0.2759,  0.6048, -0.7045,  0.9444]])

GPU, CPU

In [45]:
device = torch.device("cuda" if torch.cuda.is_available else "cpu")

In [46]:
## moving
x = torch.randn(2,2).to(device)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [48]:
## creating in GPU
z = torch.randn(9, device = device)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

## Autograd

Autograd provides automatic differentiation for all operations on Tensors.

It’s a system that automatically calculates gradients (derivatives) for tensors.

**How does it work in practice?**


1. You create tensors with requires_grad=True.

2. Perform operations on them — PyTorch remembers how they were created.

3. Call .backward() on a result tensor to compute gradients.

4. Access .grad on the original tensors to see their gradients.
