<a href="https://colab.research.google.com/github/ujjwalkuikel/PyTorch-Learning/blob/main/Pytorch_crash_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Basics

Tensor is a multidimensional matrix containing elements of single data types.

Tensors are just a flexible way to store and work with numbers, no matter how many dimensions.

In [3]:
import torch

Empty tensors

In [4]:
x = torch.empty(1);
print(x);

x = torch.empty(2,3);
print(x);

x = torch.empty(2,3,4);
print(x);

tensor([1.1107])
tensor([[ 9.2011e-33,  0.0000e+00,  9.1994e-33],
        [ 0.0000e+00, -3.1962e+12,  7.7174e-34]])
tensor([[[0.0000e+00, 1.7927e-37, 0.0000e+00, 0.0000e+00],
         [1.7192e-37, 0.0000e+00, 0.0000e+00, 9.5008e-43],
         [9.5709e-43, 0.0000e+00, 2.0319e-43, 0.0000e+00]],

        [[9.2033e-33, 0.0000e+00, 1.1107e+00, 4.5623e-41],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 2.3262e-43]]])


In [5]:
x = torch.rand(5,3)
print(x)

tensor([[0.4078, 0.1731, 0.8734],
        [0.5298, 0.7077, 0.0092],
        [0.5149, 0.1595, 0.9871],
        [0.5503, 0.2027, 0.0090],
        [0.3119, 0.5442, 0.2859]])


In [6]:
torch.zeros(5,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
y = torch.ones(2,5)

In [8]:
y.size()

torch.Size([2, 5])

In [9]:
print(x.dtype)

torch.float32


Datatype can be specified like
tensor.zeroes(2,3,dtype = torch.float16)

In [10]:
torch.ones(2,5,5, dtype = torch.int32)

tensor([[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]], dtype=torch.int32)

In [11]:
x = torch.tensor([2,5])
print(x, x.dtype)

tensor([2, 5]) torch.int64


By default require_grad is False.
It means it will need to calc gradient for this tensor.


Gradients tell us:
Which way and how much to tweak these numbers to improve the outcome.


In [12]:
x = torch.tensor([2,5], requires_grad=False)


In [13]:
# #Operations
# z = x+y
# # or
# torch.add(x,y)

RuntimeError: The size of tensor a (2) must match the size of tensor b (5) at non-singleton dimension 1

In [14]:
#To reshape tensor "view"

x = torch.randn(4,4)

y= x.view(16)

In [15]:
abc = x.numpy()

In [16]:
print(type(abc))

<class 'numpy.ndarray'>


In [17]:
# numpy to tensor
tensor = torch.from_numpy(abc)
tensor

tensor([[-0.4582, -0.8016,  1.4837, -1.2320],
        [-0.5063,  0.0940,  1.0205, -0.4903],
        [-0.6697, -0.8727,  0.8178,  2.1741],
        [ 0.9731,  1.0271,  1.2378, -0.9583]])

In [18]:
torch.tensor(abc)

tensor([[-0.4582, -0.8016,  1.4837, -1.2320],
        [-0.5063,  0.0940,  1.0205, -0.4903],
        [-0.6697, -0.8727,  0.8178,  2.1741],
        [ 0.9731,  1.0271,  1.2378, -0.9583]])

GPU, CPU

In [19]:
device = torch.device("cuda" if torch.cuda.is_available else "cpu")

In [20]:
## moving
x = torch.randn(2,2).to(device)

In [21]:
## creating in GPU
z = torch.randn(9, device = device)

## Autograd

Autograd provides automatic differentiation for all operations on Tensors.

It’s a system that automatically calculates gradients (derivatives) for tensors.

**How does it work in practice?**


1. You create tensors with requires_grad=True.

2. Perform operations on them — PyTorch remembers how they were created.

3. Call .backward() on a result tensor to compute gradients.

4. Access .grad on the original tensors to see their gradients.


**What is torch.autograd?**

-> torch.autograd is the PyTorch submodule that powers automatic differentiation — it’s short for "automatic gradient".


Think of it as the engine that:
* Records how tensors were computed (the computation graph),
* And then computes the gradients (backward pass) when asked.

In [22]:
x = torch.randn(3,requires_grad = True)

In [23]:
y = x+2

print(x)

print(y)

print(y.grad_fn)

tensor([ 1.2899,  0.6815, -1.4241], requires_grad=True)
tensor([3.2899, 2.6815, 0.5759], grad_fn=<AddBackward0>)


In [24]:
z = 3*y**2
print(z)

tensor([32.4695, 21.5716,  0.9951], grad_fn=<MulBackward0>)


In [25]:
z = z.mean()
print(z)

tensor(18.3454, grad_fn=<MeanBackward0>)


In [26]:
print(x.grad)

None


In [27]:
z.backward()
print(x.grad)

tensor([6.5797, 5.3630, 1.1518])


`.backward()` accumulates the gradient for this tensor into .grad attribute

Also, be careful during optmization. `optimizer.zero_grad()`


To stop a tensor from tracking history
we can use


*   `x.requires_grad(false)`
* `x.detach()`
*   wrap in `with torch.nograd():


---



In [28]:
a = torch.randn(2,2)

In [29]:
b = (a*a).sum()

In [30]:
print(a.requires_grad)

False


In [31]:
a = torch.randn(3,3)
a.requires_grad_(True)
b = (a*a).sum()
print(a.requires_grad)
print(b.grad_fn)

True


In [32]:
print(b.requires_grad)

True


In [33]:
b = a.detach()
print(b)

tensor([[ 1.4779,  0.9963,  0.7555],
        [-0.7122,  0.7583,  0.2316],
        [-0.6261,  1.0752, -0.6383]])


In [34]:
a = torch.randn(3,3)
a.requires_grad_(True)
b = (a*a).sum()
print(a.requires_grad)
print(b.grad_fn)

True


In [35]:
with torch.no_grad():
  b = (a*a).sum()
  print(b.grad_fn)

None


### LR using Autograd

In [36]:
x = torch.tensor([1,2,3,4,5,6],dtype = torch.float32)
y = torch.tensor([3,6,9,12,15,18],dtype = torch.float32)

In [37]:
w = torch.tensor(0.0,dtype=torch.float32,requires_grad=True)

In [38]:
def forward(x):
  return w*x

In [39]:
def loss(y,y_pred):
  return ((y_pred-y)**2).mean()

In [40]:
x_test = 4
print(f'prediction before training: f({x_test}) = {forward(x_test).item():.3f}')

prediction before training: f(4) = 0.000


In [41]:
learning_rate = 0.01
n_epochs = 1000

for epoch in range(n_epochs):
  y_pred = forward(x)

  l = loss(y,y_pred)

  l.backward()

  with torch.no_grad():
    w-= learning_rate * w.grad


  w.grad.zero_()


print(f'prediction after training: f({x_test}) = {forward(x_test).item():.3f}')




prediction after training: f(4) = 12.000


In [42]:
x_test = 9

In [43]:
print(f'prediction after training: f({x_test}) = {forward(x_test).item():.3f}')


prediction after training: f(9) = 27.000


### Model Loss and Optimizer

Pytorch pipeline looks like


1.   Design model (input, output, forward pass with different layers)
2. Construct loss and optimizer
3. Training loop:
  * Forward = compute prediction and loss
  * backward = compute gradients
  * Update weights


In [44]:
import torch
import torch.nn as nn

In [46]:
x = torch.tensor([[1],[2],[3],[4],[5],[6]],dtype = torch.float32)
y = torch.tensor([[3],[6],[9],[12],[15],[18]],dtype = torch.float32)

In [47]:
n_samples,n_features = x.shape

In [48]:
print(f'n_samples = {n_samples},n_features = {n_features}')

n_samples = 6,n_features = 1


In [49]:
x_test = torch.tensor([5],dtype = torch.float32)

In [51]:
class LinearRegression(nn.Module):
  def __init__(self,input_dim,output_dim):
    super(LinearRegression, self).__init__()

    self.lin = nn.Linear(input_dim,output_dim)


  def forward(self,x):
    return self.lin(x)

In [52]:
input_size, output_size = n_features, n_features

model = LinearRegression(input_size,output_size)

print(f'Prediction before training: {x_test.item()} = {model(x_test).item():.3f}')


Prediction before training: 5.0 = -4.356


In [57]:
#2 Define loss and optimizer
learning_rate = 0.01
n_epochs = 1000

loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate)

In [58]:
#Training Loop

for epoch in range(n_epochs):
  # predict
  y_predicted = model(x)

  #calculate loss
  l = loss(y,y_predicted)

  #calculate gradients
  l.backward()

  #update weights
  optimizer.step()

  #empty/xero gradient
  optimizer.zero_grad()

  if(epoch+1)%10 == 0:
    w,b = model.parameters()
    print(f'epoch',epoch+1 , '  w : ', w[0][0].item(), ' loss: ',l.item)

epoch 10   w :  2.98881196975708  loss:  <built-in method item of Tensor object at 0x7f2d09096390>
epoch 20   w :  2.989213705062866  loss:  <built-in method item of Tensor object at 0x7f2d090e49b0>
epoch 30   w :  2.989600896835327  loss:  <built-in method item of Tensor object at 0x7f2d24f78c50>
epoch 40   w :  2.9899742603302  loss:  <built-in method item of Tensor object at 0x7f2d09096390>
epoch 50   w :  2.9903342723846436  loss:  <built-in method item of Tensor object at 0x7f2d090e4ad0>
epoch 60   w :  2.9906811714172363  loss:  <built-in method item of Tensor object at 0x7f2d24f78c50>
epoch 70   w :  2.991015672683716  loss:  <built-in method item of Tensor object at 0x7f2d09096390>
epoch 80   w :  2.9913382530212402  loss:  <built-in method item of Tensor object at 0x7f2d090e49b0>
epoch 90   w :  2.9916493892669678  loss:  <built-in method item of Tensor object at 0x7f2d24f78c50>
epoch 100   w :  2.9919490814208984  loss:  <built-in method item of Tensor object at 0x7f2d0909639

In [59]:
print(f'Prediction after training: {x_test.item()} = {model(x_test).item():.3f}')

Prediction after training: 5.0 = 15.000
